import React, { useEffect, useMemo, useState } from 'react'

const SUBJECTS = {
  Mathematics: ['Numbers','Addition','Subtraction','Shapes'],
  English: ['Alphabet','Phonics','Reading','Writing'],
  EVS: ['Plants','Animals','My Family','School'],
}

export default function StudyMode() {
  const [classId, setClassId] = useState(Number(localStorage.getItem('study.class')) || null)
  const [query, setQuery] = useState('')
  const [expanded, setExpanded] = useState({})
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [output, setOutput] = useState(null)

  useEffect(() => { document.title = 'Study Mode' }, [])

  const subjects = useMemo(() => {
    const out = {}
    Object.entries(SUBJECTS).forEach(([sub, topics]) => {
      out[sub] = topics.filter(t => t.toLowerCase().includes(query.toLowerCase()))
    })
    return out
  }, [query])

  const toggle = (sub) => setExpanded(prev => ({...prev, [sub]: !prev[sub]}))

  const generate = async () => {
    setLoading(true); setError(''); setOutput(null)
    try {
      await new Promise(r => setTimeout(r, 3500))
      setOutput({
        notes: 'Here are concise notes generated by AI for your selected topic.',
        refs: ['https://ncert.nic.in/','https://en.wikipedia.org/'],
        language: 'English',
      })
    } catch(e) {
      setError('Failed to generate content. Please try again.')
    } finally { setLoading(false) }
  }

  return (
    <div className="space-y-6">
      {/* Class selection */}
      {!classId && (
        <section className="surface-card ios-shadow rounded-2xl p-6">
          <h2 className="text-lg font-semibold mb-3">Choose a class</h2>
          <div className="grid grid-cols-3 gap-3">
            {[1,2,3,4,5,6].map(id => (
              <button key={id} onClick={()=>{ setClassId(id); localStorage.setItem('study.class', String(id)) }} className="rounded-xl p-4 border border-black/10 dark:border-white/20 bg-white/60 dark:bg-[#1C1C1E]/60">
                <div className="font-semibold">Class {id}</div>
              </button>
            ))}
          </div>
        </section>
      )}

      {/* Syllabus + search */}
      <section className="surface-card ios-shadow rounded-2xl p-6 space-y-4">
        <div className="flex items-center justify-between gap-3">
          <h2 className="text-lg font-semibold">Syllabus</h2>
          <input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search syllabus" placeholder="Search topics" className="px-3 py-2 rounded-xl border border-black/10 dark:border-white/20 bg-white/60 dark:bg-[#1C1C1E]/60" />
        </div>
        {Object.entries(subjects).map(([sub, topics]) => (
          <div key={sub} className="border-t border-black/10 dark:border-white/10 pt-3">
            <button onClick={()=>toggle(sub)} aria-expanded={!!expanded[sub]} className="w-full text-left px-2 py-2 rounded-lg hover:bg-black/5 dark:hover:bg-white/5">
              <span className="font-medium">{sub}</span>
            </button>
            {expanded[sub] && (
              <ul className="pl-3 space-y-2">
                {topics.map(t => (<li key={t} className="opacity-80">{t}</li>))}
              </ul>
            )}
          </div>
        ))}
      </section>

      {/* AI generation */}
      <section className="surface-card ios-shadow rounded-2xl p-6 space-y-4">
        <h2 className="text-lg font-semibold">AI Content</h2>
        <div className="flex items-center gap-3">
          <button onClick={generate} className="px-4 py-2 rounded-xl bg-blue-500 text-white ios-button ios-shadow" disabled={loading}>
            {loading ? 'Generating…' : 'Generate Notes'}
          </button>
          {loading && (
            <div className="w-32 h-2 rounded-full bg-black/10 dark:bg-white/10 overflow-hidden" aria-label="Progress">
              <div className="h-full bg-blue-500 animate-pulse" style={{width:'70%'}} />
            </div>
          )}
        </div>
        {error && <p className="text-red-600">{error}</p>}
        {output && (
          <div className="space-y-3">
            <p>{output.notes}</p>
            <div className="flex gap-2 text-blue-600">
              {output.refs.map(r => (<a key={r} href={r} target="_blank" rel="noreferrer" className="underline">{r}</a>))}
            </div>
            <div className="flex items-center gap-2">
              <span className="opacity-70">Language:</span>
              <button className="px-2 py-1 rounded-lg bg-white/60 dark:bg-[#1C1C1E]/60 border border-black/10 dark:border-white/20">English</button>
              <button className="px-2 py-1 rounded-lg bg-white/60 dark:bg-[#1C1C1E]/60 border border-black/10 dark:border-white/20">Hindi</button>
            </div>
            <button className="px-3 py-2 rounded-xl bg-white/60 dark:bg-[#1C1C1E]/60 border border-black/10 dark:border-white/20">Download</button>
          </div>
        )}
      </section>
    </div>
  )
}

