import React, { useEffect, useMemo, useState } from 'react'
import { BookOpen, Search, Sparkles, Download, GraduationCap, ChevronRight, CheckCircle2 } from 'lucide-react'

const SUBJECTS = {
  Mathematics: ['Numbers', 'Addition', 'Subtraction', 'Shapes', 'Measurements', 'Data Handling'],
  English: ['Alphabet', 'Phonics', 'Reading', 'Writing', 'Grammar', 'Vocabulary'],
  EVS: ['Plants', 'Animals', 'My Family', 'School', 'Food', 'Water'],
}

export default function StudyMode() {
  const [classId, setClassId] = useState(Number(localStorage.getItem('study.class')) || null)
  const [query, setQuery] = useState('')
  const [expanded, setExpanded] = useState({})
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [output, setOutput] = useState(null)

  useEffect(() => { document.title = 'Study Mode' }, [])

  const subjects = useMemo(() => {
    const out = {}
    Object.entries(SUBJECTS).forEach(([sub, topics]) => {
      out[sub] = topics.filter(t => t.toLowerCase().includes(query.toLowerCase()))
    })
    return out
  }, [query])

  const toggle = (sub) => setExpanded(prev => ({ ...prev, [sub]: !prev[sub] }))

  const generate = async () => {
    setLoading(true); setError(''); setOutput(null)
    try {
      await new Promise(r => setTimeout(r, 3500))
      setOutput({
        notes: 'Here are concise notes generated by AI for your selected topic. The content covers key concepts, examples, and practice questions suitable for the selected class level.',
        refs: ['https://ncert.nic.in/', 'https://en.wikipedia.org/'],
        language: 'English',
      })
    } catch (e) {
      setError('Failed to generate content. Please try again.')
    } finally { setLoading(false) }
  }

  return (
    <div className="max-w-7xl mx-auto p-4 lg:p-8 space-y-8 font-sans text-[#1E1E24] dark:text-white">
      <header className="mb-8">
        <h1 className="text-4xl font-extrabold text-[#1E1E24] mb-2 dark:text-white">Study Mode</h1>
        <p className="text-[#8E8E93] text-lg dark:text-gray-400">Access your curriculum and AI-assisted learning tools</p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column - Class Selection & Syllabus */}
        <div className="lg:col-span-8 space-y-6">
          {/* Class Selection */}
          {!classId && (
            <div className="bento-card-purple p-8 rounded-[2rem] relative overflow-hidden">
              <div className="relative z-10">
                <div className="flex items-center gap-4 mb-6">
                  <div className="w-12 h-12 bg-white/20 rounded-full flex items-center justify-center backdrop-blur-sm">
                    <GraduationCap className="text-white" size={24} />
                  </div>
                  <h2 className="text-2xl font-bold text-white">Select Your Class</h2>
                </div>
                <div className="grid grid-cols-3 sm:grid-cols-6 gap-3">
                  {[1, 2, 3, 4, 5, 6].map(id => (
                    <button
                      key={id}
                      onClick={() => { setClassId(id); localStorage.setItem('study.class', String(id)) }}
                      className="aspect-square rounded-2xl bg-white/10 hover:bg-white/20 backdrop-blur-md border border-white/20 flex flex-col items-center justify-center text-white transition-all duration-200"
                    >
                      <span className="text-2xl font-bold">{id}</span>
                      <span className="text-xs opacity-80">Class</span>
                    </button>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* Syllabus Search & List */}
          <div className="bento-card p-6 min-h-[500px] dark:bg-[#1E1E24] dark:border dark:border-white/10">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-6">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-orange-100 flex items-center justify-center text-orange-600 dark:bg-orange-900/30 dark:text-orange-400">
                  <BookOpen size={20} />
                </div>
                <h2 className="text-xl font-bold text-[#1E1E24] dark:text-white">Syllabus</h2>
              </div>
              <div className="relative w-full sm:w-64">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                <input
                  value={query}
                  onChange={e => setQuery(e.target.value)}
                  placeholder="Search topics..."
                  className="w-full pl-10 pr-4 py-2 bg-gray-50 border-none rounded-xl text-sm focus:ring-2 focus:ring-orange-500/20 transition-all dark:bg-white/5 dark:text-white"
                />
              </div>
            </div>

            <div className="space-y-4">
              {Object.entries(subjects).map(([sub, topics]) => (
                <div key={sub} className="border border-gray-100 rounded-2xl overflow-hidden dark:border-white/10">
                  <button
                    onClick={() => toggle(sub)}
                    className="w-full flex items-center justify-between p-4 bg-gray-50/50 hover:bg-gray-50 transition-colors dark:bg-white/5 dark:hover:bg-white/10"
                  >
                    <span className="font-bold text-[#1E1E24] dark:text-white">{sub}</span>
                    <ChevronRight
                      size={20}
                      className={`text-gray-400 transition-transform duration-200 ${expanded[sub] ? 'rotate-90' : ''}`}
                    />
                  </button>
                  {expanded[sub] && (
                    <div className="p-4 bg-white grid grid-cols-1 sm:grid-cols-2 gap-2 dark:bg-transparent">
                      {topics.map(t => (
                        <div key={t} className="flex items-center gap-2 p-2 rounded-lg hover:bg-gray-50 text-sm text-[#8E8E93] cursor-pointer group dark:text-gray-400 dark:hover:bg-white/5">
                          <div className="w-1.5 h-1.5 rounded-full bg-gray-300 group-hover:bg-orange-400 transition-colors" />
                          {t}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column - AI Generator */}
        <div className="lg:col-span-4 space-y-6">
          <div className="bento-card-orange p-6 rounded-[2rem] text-white">
            <div className="flex items-center gap-3 mb-4">
              <Sparkles size={24} className="text-white/90" />
              <h2 className="text-xl font-bold">AI Tutor</h2>
            </div>
            <p className="text-white/80 mb-6 text-sm">
              Generate concise study notes, summaries, and practice questions instantly.
            </p>

            <button
              onClick={generate}
              disabled={loading}
              className="w-full py-3 px-4 bg-white text-orange-600 rounded-xl font-bold hover:bg-white/90 disabled:opacity-70 transition-all flex items-center justify-center gap-2"
            >
              {loading ? (
                <>
                  <div className="w-4 h-4 border-2 border-orange-600 border-t-transparent rounded-full animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles size={18} />
                  Generate Notes
                </>
              )}
            </button>
          </div>

          {output && (
            <div className="bento-card p-6 animate-in fade-in slide-in-from-bottom-4 duration-500 dark:bg-[#1E1E24] dark:border dark:border-white/10">
              <div className="flex items-center justify-between mb-4">
                <h3 className="font-bold text-[#1E1E24] dark:text-white">Generated Notes</h3>
                <span className="px-2 py-1 bg-green-100 text-green-700 text-xs font-medium rounded-lg flex items-center gap-1 dark:bg-green-900/30 dark:text-green-400">
                  <CheckCircle2 size={12} /> Ready
                </span>
              </div>
              
              <div className="prose prose-sm max-w-none mb-6 text-[#8E8E93] dark:text-gray-400">
                <p>{output.notes}</p>
              </div>

              <div className="space-y-4">
                <div>
                  <p className="text-xs font-semibold text-[#1E1E24] mb-2 uppercase tracking-wider dark:text-white">References</p>
                  <div className="flex flex-wrap gap-2">
                    {output.refs.map(r => (
                      <a
                        key={r}
                        href={r}
                        target="_blank"
                        rel="noreferrer"
                        className="text-xs text-blue-600 bg-blue-50 px-2 py-1 rounded-md hover:bg-blue-100 transition-colors truncate max-w-[150px] dark:bg-blue-900/30 dark:text-blue-400 dark:hover:bg-blue-900/50"
                      >
                        {new URL(r).hostname}
                      </a>
                    ))}
                  </div>
                </div>

                <div className="pt-4 border-t border-gray-100 flex items-center justify-between dark:border-white/10">
                  <div className="flex gap-2">
                    <button className="px-3 py-1.5 bg-gray-100 hover:bg-gray-200 rounded-lg text-xs font-medium transition-colors dark:bg-white/10 dark:hover:bg-white/20 dark:text-white">English</button>
                    <button className="px-3 py-1.5 bg-gray-100 hover:bg-gray-200 rounded-lg text-xs font-medium transition-colors opacity-50 dark:bg-white/10 dark:hover:bg-white/20 dark:text-white">Hindi</button>
                  </div>
                  <button className="p-2 text-gray-400 hover:text-[#1E1E24] transition-colors dark:hover:text-white">
                    <Download size={18} />
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
